### ISSUE TITLE
Invalid DOM property `crossorigin`. Did you mean `crossOrigin`? (Front-end)

### ISSUE THREAD

**Issue by pankeshpatel** [pankeshpatel/bmw-material-planner-assistant#45]
Warning: Invalid DOM property `crossorigin`. Did you mean `crossOrigin`?
    at link
    at head
    at DeferrableHead
    at Head (webpack-internal:///./node_modules/next/dist/pages/_document.js:185:1)
    at html
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:150:73)
    at CustomDocument (webpack-internal:///./src/pages/_document.js:19:1)

**Comment by pankeshpatel** [comment]
@JINU98 : Please look into this

**Comment by pankeshpatel** [comment]
fixed by @JINU98
