### ISSUE TITLE
undefinded on frontend

### ISSUE THREAD

**Issue by pankeshpatel** [pankeshpatel/bmw-material-planner-assistant#46]
healthResponse?.total_qty_instances?.map((val)=>{return val.total_quantity}) undefined
Warning: React does not recognize the `healthGuage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `healthguage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Paper (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Paper/Paper.js:94:44)
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Card (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Card/Card.js:60:44)
    at PartLookUp (webpack-internal:///./src/components/healthscore/part-lookup.js:130:97)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Grid (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Grid/Grid.js:270:49)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Grid (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Grid/Grid.js:270:49)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Container (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Container/Container.js:102:44)
    at main
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Box (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/createBox.js:40:41)
    at Dashboard (webpack-internal:///./src/pages/healthScore.js:26:100)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Box (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/createBox.js:40:41)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at DashboardLayout (webpack-internal:///./src/components/common/dashboard-layout.js:35:13)
    at InnerThemeProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:29:39)
    at ThemeProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:55:5)
    at ThemeProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:49:5)
    at LocalizationProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/lab/node/LocalizationProvider/LocalizationProvider.js:32:5)
    at App (webpack-internal:///./src/pages/_app.js:42:13)
    at StyleRegistry (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/next/dist/server/render.js:715:21)
Warning: React does not recognize the `setHealthGuage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `sethealthguage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Paper (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Paper/Paper.js:94:44)
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Card (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Card/Card.js:60:44)
    at PartLookUp (webpack-internal:///./src/components/healthscore/part-lookup.js:130:97)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Grid (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Grid/Grid.js:270:49)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Grid (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Grid/Grid.js:270:49)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Container (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/material/node/Container/Container.js:102:44)
    at main
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Box (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/createBox.js:40:41)
    at Dashboard (webpack-internal:///./src/pages/healthScore.js:26:100)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at Box (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/createBox.js:40:41)
    at div
    at /Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@emotion/react/dist/emotion-element-ce965253.cjs.dev.js:51:25
    at DashboardLayout (webpack-internal:///./src/components/common/dashboard-layout.js:35:13)
    at InnerThemeProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:29:39)
    at ThemeProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:55:5)
    at ThemeProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/system/ThemeProvider/ThemeProvider.js:49:5)
    at LocalizationProvider (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/@mui/lab/node/LocalizationProvider/LocalizationProvider.js:32:5)
    at App (webpack-internal:///./src/pages/_app.js:42:13)
    at StyleRegistry (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/pankeshpatel/Desktop/bmw-material-planner-assistant/frontend/node_modules/next/dist/server/render.js:715:21)
healthResponse?.total_qty_instances?.map((val)=>{return val.total_quantity}) undefined

**Comment by pankeshpatel** [comment]
@JINU98 : Please look into this.
