### ISSUE TITLE
cross-Origin (Front-end)

### ISSUE THREAD

**Issue by pankeshpatel** [pankeshpatel/bmw-material-planner-assistant#52]
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 659 ms (990 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 714 ms (1748 modules)
Warning: Received `true` for a non-boolean attribute `crossOrigin`.

If you want to write it to the DOM, pass a string instead: crossOrigin="true" or crossOrigin={value.toString()}.
    at link
    at head
    at DeferrableHead
    at Head (webpack-internal:///./node_modules/next/dist/pages/_document.js:185:1)
    at html
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:150:73)
    at CustomDocument (webpack-internal:///./src/pages/_document.js:19:1)
```

**Comment by pankeshpatel** [comment]
fixed by @ManishChaudhary-0
